//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace SIGEFA.net.miasoftware.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceConsultaRUCBinding", Namespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl")]
    public partial class ServiceConsultaRUC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaRUCOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaANEXOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceConsultaRUC() {
            this.Url = global::SIGEFA.Properties.Settings.Default.SIGEFA_net_miasoftware_webservice_ServiceConsultaRUC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaRUCCompletedEventHandler consultaRUCCompleted;
        
        /// <remarks/>
        public event consultaANEXOCompletedEventHandler consultaANEXOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://webservice.miasoftware.net/service/sunat/ws_sunat.php/consultaRUC", RequestNamespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl", ResponseNamespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string consultaRUC(string ruc, string username, string hash, string tracking) {
            object[] results = this.Invoke("consultaRUC", new object[] {
                        ruc,
                        username,
                        hash,
                        tracking});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaRUCAsync(string ruc, string username, string hash, string tracking) {
            this.consultaRUCAsync(ruc, username, hash, tracking, null);
        }
        
        /// <remarks/>
        public void consultaRUCAsync(string ruc, string username, string hash, string tracking, object userState) {
            if ((this.consultaRUCOperationCompleted == null)) {
                this.consultaRUCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaRUCOperationCompleted);
            }
            this.InvokeAsync("consultaRUC", new object[] {
                        ruc,
                        username,
                        hash,
                        tracking}, this.consultaRUCOperationCompleted, userState);
        }
        
        private void OnconsultaRUCOperationCompleted(object arg) {
            if ((this.consultaRUCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaRUCCompleted(this, new consultaRUCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://webservice.miasoftware.net/service/sunat/ws_sunat.php/consultaANEXO", RequestNamespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl", ResponseNamespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string consultaANEXO(string ruc, string username, string hash, string tracking) {
            object[] results = this.Invoke("consultaANEXO", new object[] {
                        ruc,
                        username,
                        hash,
                        tracking});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaANEXOAsync(string ruc, string username, string hash, string tracking) {
            this.consultaANEXOAsync(ruc, username, hash, tracking, null);
        }
        
        /// <remarks/>
        public void consultaANEXOAsync(string ruc, string username, string hash, string tracking, object userState) {
            if ((this.consultaANEXOOperationCompleted == null)) {
                this.consultaANEXOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaANEXOOperationCompleted);
            }
            this.InvokeAsync("consultaANEXO", new object[] {
                        ruc,
                        username,
                        hash,
                        tracking}, this.consultaANEXOOperationCompleted, userState);
        }
        
        private void OnconsultaANEXOOperationCompleted(object arg) {
            if ((this.consultaANEXOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaANEXOCompleted(this, new consultaANEXOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultaRUCCompletedEventHandler(object sender, consultaRUCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaRUCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaRUCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void consultaANEXOCompletedEventHandler(object sender, consultaANEXOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaANEXOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaANEXOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591