//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEFA.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.miasoftware.net/service/sunat/ws_sunat.php?wsdl", ConfigurationName="ServiceReference1.ServiceConsultaRUCPortType")]
    public interface ServiceConsultaRUCPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.miasoftware.net/service/sunat/ws_sunat.php/consultaRUC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string consultaRUC(string ruc, string username, string hash, string tracking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.miasoftware.net/service/sunat/ws_sunat.php/consultaANEXO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string consultaANEXO(string ruc, string username, string hash, string tracking);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceConsultaRUCPortTypeChannel : SIGEFA.ServiceReference1.ServiceConsultaRUCPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceConsultaRUCPortTypeClient : System.ServiceModel.ClientBase<SIGEFA.ServiceReference1.ServiceConsultaRUCPortType>, SIGEFA.ServiceReference1.ServiceConsultaRUCPortType {
        
        public ServiceConsultaRUCPortTypeClient() {
        }
        
        public ServiceConsultaRUCPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceConsultaRUCPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultaRUCPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultaRUCPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string consultaRUC(string ruc, string username, string hash, string tracking) {
            return base.Channel.consultaRUC(ruc, username, hash, tracking);
        }
        
        public string consultaANEXO(string ruc, string username, string hash, string tracking) {
            return base.Channel.consultaANEXO(ruc, username, hash, tracking);
        }
    }
}
